version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: lectormat-postgres
    restart: always
    environment:
      POSTGRES_USER: lectormat_user
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lectormat_db
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres-data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/seed.sql:/docker-entrypoint-initdb.d/2-seed.sql
